{
 "title": "AMQ Streams - Mirror Maker",
 "description": "Dashbard for Mirror Maker",
 "tags": [
  "kafka",
  "mirror maker",
  "amq streams"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{job=\"mm2-jmx-exporter\", topic=\"\"})"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_producer_producer_metrics_record_send_rate{job=\"mm2-jmx-exporter\"})"
    }
   ]
  },
  {
   "title": "Consumer records consumed rate",
   "type": "graph",
   "description": "The average number of records consumed per second.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "messages / second" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{job=\"mm2-jmx-exporter\"}) by (instance)",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.consumer.ConsumerTopicMetrics-AllTopics.MessagesPerSec*.OneMinuteRate, 4, 8)"
    },
    {
     "expr": "sum(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{job=\"mm2-jmx-exporter\"})",
     "legendFormat": "{{ Total }}",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.consumer.ConsumerTopicMetrics-AllTopics.MessagesPerSec*.OneMinuteRate, 4, 8)"
    }
   ]
  },
  {
   "title": "Producer record send rate",
   "type": "graph",
   "description": "The average number of records sent per second.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "messages / second" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_record_send_rate{job=\"mm2-jmx-exporter\"}",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.producer.producer-metrics.*.record-send-rate, 4, 8)"
    },
    {
     "expr": "sum(kafka_producer_producer_metrics_record_send_rate{job=\"mm2-jmx-exporter\"})",
     "legendFormat": "Total",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.producer.producer-metrics.*.record-send-rate, 4, 8)"
    }
   ]
  },
  {
   "title": "Consumer incoming byte rate",
   "type": "graph",
   "description": "The average number of bytes consumed per second.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / second" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_rate{job=\"mm2-jmx-exporter\", topic=\"\"}) by (instance)",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.consumer.ConsumerTopicMetrics-AllTopics.BytesPerSec*.OneMinuteRate, 4, 8)"
    },
    {
     "expr": "sum(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_rate{job=\"mm2-jmx-exporter\", topic=\"\"})",
     "legendFormat": "Total",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.consumer.ConsumerTopicMetrics-AllTopics.BytesPerSec*.OneMinuteRate, 4, 8)"
    }
   ]
  },
  {
   "title": "Producer outgoing byte rate",
   "type": "graph",
   "description": "The average number of outgoing bytes sent per second to all servers.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / second" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_outgoing_byte_rate{job=\"mm2-jmx-exporter\"}",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.producer.producer-metrics.*.outgoing-byte-rate, 4)"
    },
    {
     "expr": "sum(kafka_producer_producer_metrics_outgoing_byte_rate{job=\"mm2-jmx-exporter\"})",
     "legendFormat": "Total",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.producer.producer-metrics.*.outgoing-byte-rate, 4)"
    }
   ]
  },
  {
   "title": "% topic record rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "% topic messages / second" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(kafka_producer_producer_topic_metrics_record_send_rate{job=\"mm2-jmx-exporter\"}) by (topic) > 0)",
     "legendFormat": "{{ topic }}",
     "target": "aliasByNode(highestAverage(averageAbove(kafka.mirror.$instance.kafka-mirror.*.kafka.server.FetcherLagMetrics.ConsumerLag.*.Value, 1), 20), 4, 9)"
    }
   ]
  },
  {
   "title": "% topic bytes rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps", "label": "% topic bytes / second" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_rate{job=\"mm2-jmx-exporter\", topic!=\"\"}) by (topic) > 0)",
     "legendFormat": "{{ topic }}",
     "target": "aliasByNode(highestAverage(averageAbove(kafka.mirror.$instance.kafka-mirror.*.kafka.server.FetcherLagMetrics.ConsumerLag.*.Value, 1), 20), 4, 9)"
    }
   ]
  },
  {
   "title": "Consumer lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none", "label": "messages" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag{job=\"mm2-jmx-exporter\"}",
     "legendFormat": "{{ topic }} [{{ partition }}]",
     "target": "aliasByNode(highestAverage(averageAbove(kafka.mirror.$instance.kafka-mirror.*.kafka.server.FetcherLagMetrics.ConsumerLag.*.Value, 1), 20), 4, 9)"
    }
   ]
  },
  {
   "title": "Consumer lag average",
   "type": "graph",
   "description": ".",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag_avg{job=\"mm2-jmx-exporter\"}",
     "legendFormat": "{{ topic }} [{{ partition }}]",
     "target": "aliasByNode(highestAverage(averageAbove(kafka.mirror.$instance.kafka-mirror.*.kafka.server.FetcherLagMetrics.ConsumerLag.*.Value, 1), 20), 4, 9)"
    }
   ]
  },
  {
   "title": "Consumer lag max",
   "type": "graph",
   "description": "The maximum lag in terms of number of records for any partition in this window. An increasing value over time is your best indication that the consumer group is not keeping up with the producers.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag_max{job=\"mm2-jmx-exporter\"}",
     "legendFormat": "{{ topic }} [{{ partition }}]",
     "target": "aliasByNode(highestAverage(averageAbove(kafka.mirror.$instance.kafka-mirror.*.kafka.server.FetcherLagMetrics.ConsumerLag.*.Value, 1), 20), 4, 9)"
    }
   ]
  },
  {
   "title": "Consumer fetch request rate",
   "type": "graph",
   "description": "The number of fetch requests per second.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short", "label": "requests / second" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_consumer_fetch_manager_metrics_fetch_rate{job=\"mm2-jmx-exporter\"}) by (instance)",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.server.FetcherStats.RequestsPerSec*.OneMinuteRate, 4, 8)"
    }
   ]
  },
  {
   "title": "Producer dropped message rate",
   "type": "graph",
   "description": "time taken for a group rejoin",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "none", "label": "messages / second" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_tools_mirrormaker_value{job=\"mm2-jmx-exporter\",name=\"MirrorMaker-numDroppedMessages\"}[5m])",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(highestAverage(averageAbove(kafka.mirror.$instance.kafka-mirror.*.kafka.server.FetcherLagMetrics.ConsumerLag.*.Value, 1), 20), 4, 9)"
    }
   ]
  },
  {
   "title": "Consumer fetch request latency",
   "type": "graph",
   "description": "The average and max request latency in ms.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "none", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumer_consumer_fetch_manager_metrics_fetch_latency_avg{job=\"mm2-jmx-exporter\"}) by (instance)",
     "legendFormat": "{{instance}} (average)",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.producer.producer-metrics.*.request-latency-avg, 4)"
    },
    {
     "expr": "max(kafka_consumer_consumer_fetch_manager_metrics_fetch_latency_max{job=\"mm2-jmx-exporter\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Produce request rate",
   "type": "graph",
   "description": "The average number of outgoing bytes sent per second to all servers.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "none", "label": "requests / second" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_request_rate{job=\"mm2-jmx-exporter\"}",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.producer.producer-metrics.*.request-rate, 4)"
    }
   ]
  },
  {
   "title": "Consume request latency per node",
   "type": "graph",
   "description": "The average and max request latency in ms.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "none", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumer_consumer_node_metrics_request_latency_avg{job=\"mm2-jmx-exporter\",node_id!~\"^node(-2147482644|--[\\\\d+])\"}) by (instance, client_id)",
     "legendFormat": "{{instance}} {{client_id}} {{node_id}} (average)",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.producer.producer-metrics.*.request-latency-avg, 4)"
    },
    {
     "expr": "max(kafka_consumer_consumer_node_metrics_request_latency_max{job=\"mm2-jmx-exporter\",node_id!~\"^node(-2147482644|--[\\\\d+])\"}) by (instance, client_id)",
     "legendFormat": "{{instance}} {{client_id}} {{node_id}} (max)"
    }
   ]
  },
  {
   "title": "Produce request latency average",
   "type": "graph",
   "description": "The average and max request latency in ms.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "none", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_request_latency_avg{job=\"mm2-jmx-exporter\"}",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.producer.producer-metrics.*.request-latency-avg, 4)"
    },
    {
     "expr": "max(kafka_producer_producer_metrics_request_latency_max{job=\"mm2-jmx-exporter\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Owned partitions per host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "none", "label": "partitions" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_consumer_coordinator_metrics_assigned_partitions{job=\"mm2-jmx-exporter\"}) by (instance)",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(averageAbove(kafka.mirror.$instance.kafka-mirror.*.kafka.consumer.ZookeeperConsumerConnector.OwnedPartitionsCount.*.Value, 1), 4, 9)"
    },
    {
     "expr": "sum(kafka_consumer_consumer_coordinator_metrics_assigned_partitions{job=\"mm2-jmx-exporter\"})",
     "legendFormat": "Total partitions owned",
     "target": "aliasByNode(averageAbove(kafka.mirror.$instance.kafka-mirror.*.kafka.consumer.ZookeeperConsumerConnector.OwnedPartitionsCount.*.Value, 1), 4, 9)"
    }
   ]
  },
  {
   "title": "Produce request latency average (producer -> broker node)",
   "type": "graph",
   "description": "The average and max request latency in ms.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "none", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_node_metrics_request_latency_avg{job=\"mm2-jmx-exporter\",node_id!~\"^node(-2147482644|--[\\\\d+])\"}",
     "legendFormat": "{{instance}} -> {{node_id}} ",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.producer.producer-metrics.*.request-latency-avg, 4)"
    },
    {
     "expr": "max(kafka_producer_producer_node_metrics_request_latency_max{job=\"mm2-jmx-exporter\",node_id!~\"^node(-2147482644|--[\\\\d+])\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Consumer Group Join Time",
   "type": "graph",
   "description": "time taken for a group rejoin",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "none", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_join_time_avg{job=\"mm2-jmx-exporter\"}",
     "legendFormat": "{{ instance }} {{ client_id }} (average)",
     "target": "aliasByNode(highestAverage(averageAbove(kafka.mirror.$instance.kafka-mirror.*.kafka.server.FetcherLagMetrics.ConsumerLag.*.Value, 1), 20), 4, 9)"
    },
    {
     "expr": "max(kafka_consumer_consumer_coordinator_metrics_join_time_max{job=\"mm2-jmx-exporter\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Producer requests in flight",
   "type": "graph",
   "description": "The current number of in-flight requests awaiting a response.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "none", "label": "requests" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_requests_in_flight{job=\"mm2-jmx-exporter\"}",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.producer.producer-metrics.*.requests-in-flight, 4)"
    }
   ]
  },
  {
   "title": "Consumer commit rate per host",
   "type": "graph",
   "description": "The number of commit calls per second",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short", "label": "commits / second" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_consumer_coordinator_metrics_commit_rate{job=\"mm2-jmx-exporter\"}) by (instance)",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.server.FetcherStats.RequestsPerSec*.OneMinuteRate, 4, 8)"
    }
   ]
  },
  {
   "title": "Producer buffer % used",
   "type": "graph",
   "description": "The total amount of buffer memory that is not being used (either unallocated or in the free list).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "percentunit", "label": "% buffer used" }
   ],
   "targets": [
    {
     "expr": "1 - (kafka_producer_producer_metrics_buffer_available_bytes{job=\"mm2-jmx-exporter\"} / kafka_producer_producer_metrics_buffer_total_bytes{job=\"mm2-jmx-exporter\"})",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.producer.producer-metrics.*.request-rate, 4)"
    }
   ]
  },
  {
   "title": "Produce request batch size average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_batch_size_avg{job=\"mm2-jmx-exporter\"}",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.producer.producer-metrics.*.request-rate, 4)"
    },
    {
     "expr": "max(kafka_producer_producer_metrics_batch_size_max{job=\"mm2-jmx-exporter\"})",
     "legendFormat": "max",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.producer.producer-metrics.*.request-rate, 4)"
    }
   ]
  },
  {
   "title": "Producer record retry & error rate",
   "type": "graph",
   "description": "The average per-second number of record sends that resulted in errors or retries.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "none", "label": "# / second" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_record_error_rate{job=\"mm2-jmx-exporter\"}",
     "legendFormat": "{{instance}} (error)",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.producer.producer-metrics.*.record-retry-rate, 4, 9)"
    },
    {
     "expr": "kafka_producer_producer_metrics_record_retry_rate{job=\"mm2-jmx-exporter\"}",
     "legendFormat": "{{instance}} (retry)",
     "target": "aliasByNode(kafka.mirror.$instance.kafka-mirror.*.kafka.producer.producer-metrics.*.record-error-rate, 4, 9)"
    }
   ]
  },
  {
   "title": "Produce buffer exhausted rate",
   "type": "graph",
   "description": "The average per-second number of record sends that are dropped due to buffer exhaustion",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "none", "label": "messages / second" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_buffer_exhausted_rate{job=\"mm2-jmx-exporter\"}",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(highestAverage(averageAbove(kafka.mirror.$instance.kafka-mirror.*.kafka.server.FetcherLagMetrics.ConsumerLag.*.Value, 1), 20), 4, 9)"
    }
   ]
  }
 ]
}